### ISSUE TITLE
Error "billing hard limit reached" on first attempt with a new api key

### ISSUE THREAD

**Issue by machinemessiah** [duffey/spicetify-ai-playlist-images#1]
This is the data returned by the request to `https://api.openai.com/v1/images/generations` (code 400):
```json
{
    "code": "billing_hard_limit_reached",
    "message": "Billing hard limit has been reached",
    "param": null,
    "type": "invalid_request_error"
}
```
API key is stored with the key `spicetify-ai-playlist-images:openai-api-key` in local storage, so no issue with that.

Subsequent attempts have the same result.

**Comment by duffey** [comment]
Seems pretty self-explanatory. I think you need to check your OpenAI settings.

**Comment by machinemessiah** [comment]
> Seems pretty self-explanatory. I think you need to check your OpenAI settings.

I wasn't aware this required a GPT4 subscription, I assumed it was using GPT3.

**Comment by duffey** [comment]
Ah, OK. I'm not sure. I might need to add a better error message
