### ISSUE TITLE
Extension not found

### ISSUE THREAD

**Issue by Rairof** [duffey/spicetify-ai-playlist-images#2]
There are no extension named "AI Playlist Images" in the marketplace so I dont know how to install your extension

![image](https://github.com/duffey/spicetify-ai-playlist-images/assets/107706560/1fbd8e37-e820-49ab-99b3-3ef03bfa28f8)

**Comment by duffey** [comment]
Yeah, I don't know why. If you click load more it appears though.

**Comment by Rairof** [comment]
weird indeed but thanks!
