### ISSUE TITLE
Image generated but not set

### ISSUE THREAD

**Issue by JustSxm** [duffey/spicetify-ai-playlist-images#4]
The image is generated via OpenAI API (I see my balance going down), but it doesn't seem to set the image and I have no idea how to recover it.

**Comment by duffey** [comment]
Hey, I think it was due to the proxy no longer working. I fixed this before, but I forgot to update the dist file for Marketplace. It should work as soon as it hits the Marketplace.

**Comment by duffey** [comment]
Oh, and unfortunately there is no way to recover the image unless it happens to appear in your dev console. Sorry about that.

**Comment by JustSxm** [comment]
I figured, I just used to console to get the link and apply it myself

Thanks!
